### ISSUE TITLE
can't run on Openwrt barrier breaker

### ISSUE THREAD

**Issue by killerhehe** [el1n/OpenWRT-package-softether#12]
softethervpn_4.14-9529_ar71xx.ipk
root@OpenWrt:~# /usr/bin/vpnserver start
-- Alert: SoftEther VPN Kernel --
String Library Init Failed.
Please check your locale settings and iconv() libraries.
root@OpenWrt:~#

**Comment by Alberts00** [comment]
Please read the README.md
In particular

"If you want run SoftEther VPN in a shell, You need set the LANG environment variable and execute the SoftEther VPN."

    /usr/bin/env LANG=en_US.UTF-8 /usr/bin/vpnserver start

**Comment by killerhehe** [comment]
Thank you so much! I didn't notice that before.And if i want to use vpnclient on openwrt,how to manage it~~Is there any Client manager?

**Comment by Alberts00** [comment]
Seems like there is a way to configure Softether vpn client remotely, though I haven't used it. I will check it out and report.
See https://www.softether.org/4-docs/1-manual/6._Command_Line_Management_Utility_Manual/6.5_VPN_Client_Management_Command_Reference
In particular "6.5.56 "RemoteEnable": Allow Remote Management of VPN Client Service"

**Comment by Alberts00** [comment]
Okay so I checked out and you can Create a new connection on your Windows PC With Softether client, export the connection, copy it to your router and there...
    root@Sandbox:~# /etc/init.d/softethervpnclient enable
    root@Sandbox:~# /etc/init.d/softethervpnclient start
    root@Sandbox:~# /usr/bin/env LANG=en_US.UTF-8 /usr/bin/vpncmd
Choose 2
Press Enter
Write NicCreate vpnclient
Write AccountImport
Write the vpn connection file path
Write AccountConnect
Write connection name
