### ISSUE TITLE
SHA0 *should* be disabled

### ISSUE THREAD

**Issue by haf** [el1n/OpenWRT-package-softether#8]
https://en.wikipedia.org/wiki/Secure_Hash_Algorithm

You should not search-replace away the `no-sha0`, as that's a very insecure algorithm.

**Comment by el1n** [comment]
you are right but not compatible with other softether binary if this problem fixed.
its probably not happy at least me.

please tell to SoftEther developer if you think this problem is very critical.

**Comment by haf** [comment]
According to their documentation they use SHA1. https://www.softether.org/1-features/3._Security_and_Reliability#Hashing_Algorithms_for_HMAC Or don't they?

**Comment by el1n** [comment]
encrypted connection uses secure algorithm.

however, for example password authentication uses SHA-0, perhaps.
authentication always failed if does not use SHA-0.

well... its safe. i guess.
because connection is encrypted.

**Comment by el1n** [comment]
btw i don't want to use SHA-0 if possible.
overwrite of libopenssl is bad method.

**Comment by el1n** [comment]
ill close bcoz fixed bad method.
